variables:
  system.debug: false
  major: 1
  minor: 0

name: $(major).$(minor).$(rev:r) #Build.BuildNumber

trigger: 
  batch: "true"
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: pipelines
    type: git
    name: Epinova - Modules/Epinova.Pipelines
    ref: refs/heads/main

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Remove-Item -Path $(System.DefaultWorkingDirectory)\dlls -Force -Recurse

- template: nuget.3.yml@pipelines
  parameters:
    dotnetVersions:
      - 6.0.x
      - 7.0.x
    workingDirectory: "$(System.DefaultWorkingDirectory)"

- task: PublishCodeCoverageResults@1
  displayName: Publish Code Coverage Results
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: $(TestResultsPath)/**/coverage.cobertura.xml